apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 7af21f6d-1280-4ffc-a888-6ab1f9bd01a4
  labels:
    azure.workload.identity/use: "true"
  name: azure-voting-app-serviceaccount
  namespace: default